name: n8n-prod

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--providers.file.filename=/traefik-certs.yml"
      - "--providers.file.watch=true"
      # - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      # - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      # Monta la carpeta de certificados del wildcard (la misma que usa el otro proyecto)
      - ./certs:/certs:ro
      # Monta el archivo de configuración de certificados de Traefik
      - ./traefik-certs.yml:/traefik-certs.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n_network
  
  redis:
    image: redis:8.8-alpine
    container_name: n8n_redis
    restart: always
    command:
      - redis-server
      - "--appendonly"
      - "yes"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - queue_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
      - MINIO_SERVER_URL=https://${MINIO_API_SUBDOMAIN}.${DOMAIN_NAME}
      # no aplicará externamente
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    volumes:
      - /var/minio-buckets:/data
    networks:
      - n8n_network
    ports:
      # Expone el puerto 9001 SOLO a la máquina local
      # Antes no necesitaba porque Traefik enrutaba internamente
      - "127.0.0.1:9001:9001"
    labels:
      - traefik.enable=true

      # Router para API / Descargas Públicas (s3-files.tudominio.com)
      - traefik.http.routers.minio-api.rule=Host(`${MINIO_API_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.minio-api.entrypoints=websecure
      - traefik.http.routers.minio-api.tls=true
      - traefik.http.routers.minio-api.service=minio-api
      - traefik.http.services.minio-api.loadbalancer.server.port=9000

      # # Router para Consola Web de Administración (bucket-store.tudominio.com)
      # - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_SUBDOMAIN}.${DOMAIN_NAME}`)
      # - traefik.http.routers.minio-console.entrypoints=websecure
      # - traefik.http.routers.minio-console.tls=true
      # - traefik.http.routers.minio-console.service=minio-console
      # - traefik.http.services.minio-console.loadbalancer.server.port=9001
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 10

  minio-setup:
    image: minio/mc
    container_name: minio_setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - n8n_network
    entrypoint: >
      /bin/sh -c "
      set -e;

      mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};

      mc mb --ignore-existing myminio/cdn-manifest;
      mc mb --ignore-existing myminio/artifacts-bak;

      mc anonymous set download myminio/cdn-manifest;
      mc anonymous set none myminio/artifacts-bak;

      touch /tmp/.keep;

      mc cp /tmp/.keep myminio/cdn-manifest/assets/.keep;
      mc cp /tmp/.keep myminio/cdn-manifest/chat/.keep;
      mc cp /tmp/.keep myminio/cdn-manifest/public/.keep;

      mc cp /tmp/.keep myminio/artifacts-bak/backups/.keep;
      mc cp /tmp/.keep myminio/artifacts-bak/chat/.keep;
      mc cp /tmp/.keep myminio/artifacts-bak/private/.keep;

      exit 0;
      "

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: always
    # En producción, no es necesario mapear el puerto a la máquina host, ya que Traefik se encargará de enrutar el tráfico al contenedor n8n
    expose:
      - "5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      # - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.entrypoints=websecure
      # Ya no necesitas especificar certresolver porque Traefik usará el certificado wildcard por defecto
      # - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=true
      - N8N_PROXY_HOPS=1
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/      
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=saacdata
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=n8n
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      # Manejo de Colas Redis
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8n_network
      - queue_network
    depends_on:
      - redis
  
  n8n-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n_worker
    restart: always
    command: ["worker", "--concurrency", "${N8N_WORKER_CONCURRENCY:-5}"]
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=saacdata
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=n8n
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      # Worker y Cola
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_WORKER_MODE=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./local-files:/files
    networks:
      - n8n_network
      - queue_network
    depends_on:
      redis:
        condition: service_healthy

networks:
  n8n_network:
    driver: bridge

  queue_network:
    driver: bridge
    internal: true

volumes:
  n8n_data:
  redis_data: