name: n8n-prod

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--providers.file.filename=/traefik-certs.yml"
      - "--providers.file.watch=true"
      # - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      # - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      # Monta la carpeta de certificados del wildcard (la misma que usa el otro proyecto)
      - ./certs:/certs:ro
      # Monta el archivo de configuración de certificados de Traefik
      - ./traefik-certs.yml:/traefik-certs.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n_network
  
  redis:
    image: redis:alpine
    container_name: n8n_redis
    restart: always
    # Solo en la red interna, sin puertos expuestos a internet
    networks:
      - n8n_network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
      # Variables clave para que la consola funcione bajo un sub-directorio
      - MINIO_SERVER_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - MINIO_BROWSER_REDIRECT_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/minio-console
    volumes:
      # Ruta absoluta en el host
      - /var/minio-buckets:/data
    networks:
      - n8n_network
    labels:
      - traefik.enable=true

      # Router para API / Descargas Públicas
      # Redirige el tráfico que empiece por el nombre del bucket hacia el puerto 9000
      - traefik.http.routers.minio-api.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`) && PathPrefix(`/cdn-manifest`)
      - traefik.http.routers.minio-api.entrypoints=websecure
      - traefik.http.routers.minio-api.tls=true
      - traefik.http.services.minio-api.loadbalancer.server.port=9000

      # Router para Consola Web de Administración
      - traefik.http.routers.minio-console.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`) && PathPrefix(`/minio-console`)
      - traefik.http.routers.minio-console.entrypoints=websecure
      - traefik.http.routers.minio-console.tls=true
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      # StripPrefix es necesario para que MinIO no reciba "/minio-console" en sus rutas internas
      - traefik.http.middlewares.minio-stripprefix.stripprefix.prefixes=/minio-console
      - traefik.http.routers.minio-console.middlewares=minio-stripprefix

  minio-setup:
    image: minio/mc
    container_name: minio_setup
    depends_on:
      - minio
    networks:
      - n8n_network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER:-admin} $${MINIO_ROOT_PASSWORD:-password123};
      mc mb myminio/cdn-manifest --ignore-existing;
      mc anonymous set download myminio/cdn-manifest;
      mc mb myminio/artifacts-bak --ignore-existing;
      exit 0;
      "

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: always
    # En producción, no es necesario mapear el puerto a la máquina host, ya que Traefik se encargará de enrutar el tráfico al contenedor n8n
    expose:
      - "5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      # - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.entrypoints=websecure
      # Ya no necesitas especificar certresolver porque Traefik usará el certificado wildcard por defecto
      # - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=true
      - N8N_PROXY_HOPS=1
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/      
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=saacdata
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=n8n
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      # Manejo de Colas Redis
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - n8n_network
    depends_on:
      - redis
  
  n8n-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n_worker
    restart: always
    command: ["worker", "--concurrency", "${N8N_WORKER_CONCURRENCY:-5}"]
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=saacdata
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=n8n
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      # Worker y Cola
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_WORKER_MODE=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    volumes:
      - ./local-files:/files
    networks:
      - n8n_network
    depends_on:
      - redis
      - n8n

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_data: